version: '3'

services:
  expo-app:
    build:
      context: .
      dockerfile: environment/Dockerfile
    container_name: guild-expo-app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "8081:8081"
    environment:
      - NODE_ENV=development
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=localhost
    command: npm run dev

  web-build:
    build:
      context: .
      dockerfile: environment/Dockerfile
    container_name: guild-expo-web-build
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    command: npm run build:web 