services:
  expo-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: guild-expo-app
    volumes:
      - ../frontend:/app
      - /app/node_modules
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "8082:8081"
      - "8083:8083"
    environment:
      - NODE_ENV=development
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=localhost
      - EXPO_PUBLIC_WEB_SOCKET_URL=ws://localhost:8083
    extra_hosts:
      - "host.docker.internal:host-gateway"
    network_mode: "host"
    command: npm run dev

  web-build:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: guild-expo-web-build
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    command: npm run build:web 